# docker build -t builddotnetcore .
# docker tag builddotnetcore kritner/builddotnetcore:dnc2.1-v1-base
# docker push kritner/builddotnetcore:dnc2.1-v1-base

FROM microsoft/dotnet:2.1-sdk
WORKDIR /app

# Perform updates, install gnupg and sudo
RUN apt-get update \
    && apt-get -y upgrade \
    && apt-get -y dist-upgrade \
    && apt-get install -y gnupg \
    && apt-get install -y sudo