# docker build -t builddotnetcore_node .
# docker tag builddotnetcore_node kritner/builddotnetcore:dnc2.1-v1-node
# docker push kritner/builddotnetcore:dnc2.1-v1-node

FROM kritner/builddotnetcore:dnc2.1-v1-base
WORKDIR /app

# Install node
RUN curl -sL deb.nodesource.com/setup_10.x | sudo -E bash - \
    && apt-get install -y nodejs